IMAGE_NAME = "my-cluster-box"
N_WORKER = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 4
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.network "forwarded_port", guest: 80, host: 80, protocol: "tcp"
        master.vm.network "forwarded_port", guest: 443, host: 443, protocol: "tcp"
        master.vm.hostname = "k8s-master"
        master.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=774','fmode=775']
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
                kubernetes_version: "1.24.0-00",
                arch: "amd64",
                os: "linux",
                containerd_version: "1.6.4",
                runc_version: "1.1.1",
                cni_version: "1.1.1"
            }
        end
    end

    (1..N_WORKER).each do |i|
        config.vm.define "k8s-worker-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "k8s-worker-#{i}"
            node.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=774','fmode=775']
            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                    kubernetes_version: "1.24.0-00",
                    arch: "amd64",
                    os: "linux",
                    containerd_version: "1.6.4",
                    runc_version: "1.1.1",
                    cni_version: "1.1.1"
                }
            end
        end
    end
end